### ISSUE TITLE
Impurity dots turn yellow in screenshot

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#171] opened 2018-08-24 18:56 UTC
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome and Firefox
**Problem description:**
For phetsims/QA/issues/179
When a screenshot is taken using the PhET menu the impurity dots appear to be the color of the background (i.e. yellow).  They should be black dots.
**Steps to reproduce:**
1. Adjust the sliders so that a fair number of impurity dots are visible.
2. Go to the PhET menu
3. Select "Screenshot"
4. Open and view the resulting image.

**Screenshots:**
![cheese](https://user-images.githubusercontent.com/41024075/44602494-03304800-a79d-11e8-9164-17e705533be9.PNG)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.8/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.8 2018-08-23 22:07:53 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"fe3cb370","branch":"HEAD"},"dot":{"sha":"56c1d4b8","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"b70a62da","branch":"HEAD"},"scenery":{"sha":"33290b5e","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"2e7beb55","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

</details>

**Comment by jessegreenberg** [comment] 2018-08-24 21:54
Almost certainly caused by #165 changes, assigning to me. I am not seeing this in other sims that use CanvasNode.

**Comment by jessegreenberg** [comment] 2018-08-24 22:45
If I add `context.fillStyle = 'black'` somewhere above  `context.fill()` in paintCanvas the problem goes away. fillStyle is supposed to have a default of black, not sure why it isnt showing up in the screenshot feature, am I wronge

**Comment by jessegreenberg** [comment] 2018-08-24 22:55
This is fixed in master, marking with a label so this makes it into the release branch.

**Comment by KatieWoe** [comment] 2018-08-24 23:02
Looks good on master

**Comment by zepumph** [comment] 2018-10-24 23:01
We will not be pulling this into the 1.5 rc. If this has been confirmed fixed in master it can be closed.

**Closed by zepumph** 2018-10-24 23:01 UTC
Labels: status:fixed-pending-testing, type:bug
