### ISSUE TITLE
NVDA Keyboard Nav Button and Phet Menu read as same button

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#176] opened 2018-09-07 18:29 UTC
**Device**
Dell Laptop
**OS**
Win 10
**Browser**
Firfox
**Problem Description**
For phetsims/QA/issues/183
First noticed by @lmulhall-phet.  When NVDA is reading through the controls it seems to treat the Keyboard Nav Button as being the same as the PhET Menu, and reads them one right after the other while only highlighting the Keyboard Nav button.  This only seems to be the case when reading through the sim description.  When tab is used to navigate with keyboard nav its self and NVDA is reading, the PhET menu is easily selected by itself.
**Steps to reproduce**
1. Use NVDA on Win 10 Firefox.
2. Using keyboard commands to read the sim description (not to navigate the controls) read through the whole description
3. The sim will highlight the reset all button when that area of the description is reached
4. Use the keyboard to advance to the next dialog
5. The keyboard nav description button will be highlighted but both it, and the PhET menu will be read
6. Attempt to advance to the next dialog with the keyboard.  The same behavior as step 5 will occur.

**Screen Capture (also showing keyboard inputs)**
https://drive.google.com/file/d/11pc6FvyPoREjfCpWCzROLsQ2SvJl1jK5/view?usp=sharing

**Comment by zepumph** [comment] 2018-09-07 20:16
I took this for a spin to hear it with chrome and firefox (NVDA), and found the same thing with both. I can confirm that I hear the same thing you do @KatieWoe, except here is my take.

I think the title is a little bit different what what is happening
>NVDA Keyboard Nav Button and Phet Menu read as same button

I actually hear two individual buttons each time, they are just described in the same key press. This is because they are both surrounded in a `div` with `role=region`. So as you arrow down, I guess everything in that region is read out to you. It is confusing though because although it is reading the whole region, the focus is just on the keyboard shortcuts button. Furthermore, you are at the last element on the screen, so each time you press the down arrow, it just repeats reading the "region div". 

To me this seems to be a UX and design question for @terracoda. I don't think there is a bug, as the code is running (I believe) as expected. @terracoda will you please look into the desired behavior of this, I'm happy to pair if you need to see it on NVDA.

Also tagging @jessegreenberg as I'm unsure how much he knows about the sim resources section. I think I was involved pretty little in that.

**Comment by terracoda** [comment] 2018-09-24 19:01
I am re-opening this issue. Based on 2 interviews with Friction, this seems to be an issue for blind users.

But maybe it makes the best sense to move this issue to the A11y Research repos as it affects all sims?

**Comment by terracoda** [comment] 2018-09-24 19:03
I am adding this item to Tuesday's A11y Dev/Design meeting, and I'll tag folks so they have a heads up: @jessegreenberg, @zepumph, @mbarlow12, @emily-phet, @elharden2

**Comment by zepumph** [comment] 2018-09-24 19:36
@terracoda I think you should create an issue in a11y research and then link this issue to it. I think these large ideas/design changes work best when not tied to a bug report from QA for a single sim.

**Comment by terracoda** [comment] 2018-09-24 19:44
Closing this issue again. It will be addressed in https://github.com/phetsims/a11y-research/issues/121 .

**Closed by terracoda** 2018-09-24 19:44 UTC
Labels: design:a11y, dev:a11y
