### ISSUE TITLE
Rho symbol does not translate

### ISSUE THREAD

**Issue by rea-laura** [phetsims/resistance-in-a-wire#187] opened 2018-11-08 17:02 UTC
<b>Test Device</b>

Pauling

<b>Operating System</b>

iOS 11.4.1

<b>Browser</b>

Safari 11.4.1

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/219:
Rho symbols in equation and in slider bar panel do not translate during string test queries. This symbol <b>does</b> translate in the <b>published version of the sim.</b>

The issue appears on all operating systems and browsers tested thus far (will update if this changes.)

<b>Steps to Reproduce</b>

1) open the dev version of the sim: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_en_phet.html
2) append URL with ?stringTest=double, ?stringTest=long, or any other string test.
3) rho character will not translate with the string tests.

<b>Visuals</b>
![image](https://user-images.githubusercontent.com/44005544/48213474-1fbf3380-e33b-11e8-995f-ca1ce06a826c.png)

**Comment by ariel-phet** [comment] 2018-11-12 22:49
@zepumph looking through old issues, I don't see anything related to the translation of rho. In fact, in an earlier round of dev testing on 1.5.0-rc.8 it seems this was translatable (https://github.com/phetsims/resistance-in-a-wire/issues/173). I know we have punted on certain things, but not sure why we wouldn't make this symbol translatable unless there was a compelling reason.

**Comment by jessegreenberg** [comment] 2018-11-13 16:10
A decision on this may have come from https://github.com/phetsims/scenery-phet/issues/353, using MathSymbols.js.

**Comment by jbphet** [comment] 2018-11-14 17:10
I read through the issue the @jessegreenberg linked above, and translatability was discussed for Trig Tour, but not for RIAW.  I just looked through the RIAW translations, and there are two simulations in which the rho symbol is translated.  One is Slovenian (locale=sl), and it looks legit to me:

![image](https://user-images.githubusercontent.com/3082831/48497959-63f67c00-e7f2-11e8-8d92-88eec679e967.png)

The other is Tibetan (locale=bo), and it looks seriously messed up, so I don't think it's worth considering in this discussion.

Since there **is** at least one translation for this symbol, and since the work done to change it to a common math symbol makes the symbol untranslatable, it's my opinion that we should revert the change and keep the rho symbol translatable.

There are also several translations of the Ohms symbol Ω, which was converted to use our common math symbols at the same time.  Here's an example from the Belarusian (locale=be) version:

Belarusian
![image](https://user-images.githubusercontent.com/3082831/48499055-c6507c00-e7f4-11e8-8d3f-a24b2f87c184.png)

That too should be reverted in my opinion.

The commit in question is https://github.com/phetsims/resistance-in-a-wire/commit/8ef7861a780ee272ab39006268eedef7f13a4f56#diff-6348d9f4d7aa9bb88a51fab3adfe0d0f.

@ariel-phet - assigning to you for any final thoughts, and if you agree with me on this please assign it back and I'll make it happen.  Tagging @zepumph in case he has any objections.

**Comment by ariel-phet** [comment] 2018-11-14 18:48
@jbphet I agree with your assessment wholeheartedly

**Comment by jbphet** [comment] 2018-11-19 18:55
I have restored the ability to translate rho (ρ) and omega (Ω) on master and on the 1.6 release branch.

**Comment by jbphet** [comment] 2018-11-26 16:19
@zepumph - I thought about this, but decided against because MathSymbols.js is common code, and I felt like this could lead to unintended consequences.  To be honest, though, I didn't spend a lot of time considering the pros and cons.  If you'd like to pursue it, and possibly discuss at dev meeting, that'd be okay with me.

**Comment by jbphet** [comment] 2018-11-26 16:21
Having said that, I'm not going to hold off publication of RIAW waiting for a resolution on this.  I don't think the consequences of publishing with this fix are too dire, and I can follow up with some adjustments to the common code file on master if necessary later.

**Comment by zepumph** [comment] 2018-11-26 18:35
That sounds like a great plan. Please proceed with RIAW publication. 

I will mark for developer meeting with one main question to discuss: "should characters in `MathSymbols.js` be translatable?"

We decided before that `MathSymbols.js` was a good place consolidating certain symbols, but in this issue we found that doing that for "ohms" disabled translation. 

I personally think it would be best to make symbols in that file translatable, but I don't necessarily know if there are drawbacks to having translatables like that in common code, and/or if there will be complications if the same symbol, used in multiple sims, is translated into different things depending on context.

**Comment by pixelzoom** [comment] 2018-11-29 18:04
@jessegreenberg I guess it depends on what you mean by "math symbols".  In Graphing Lines, Graphing Quadratics and similar sims, we decided to localize x,y,a,b,c,m, etc.  And we've seen that a couple of translators have actually changed these.

**Comment by jessegreenberg** [comment] 2018-11-29 18:32
Looks like symbols removed from translatable strings in that issue were infinity, pi, plus/minus, and theta, and it makes sense that those are not translatable. x and y were left for i18n.

**Comment by pixelzoom** [comment] 2018-12-06 02:48
@zepumph Is there still something here that we need to discuss at developer meeting?

**Comment by zepumph** [comment] 2018-12-06 17:53
>@zepumph Is there still something here that we need to discuss at developer meeting?

Yes the main question is if we, as a team, allow translatable strings in `MathSymbols.js`. I didn't know if it went against what people expected that file to look like. I think this issue should be solved by adding `ohms` back to `MathSymbols.js` as a translatable string.

>Looks like symbols removed from translatable strings in that [trig tour] issue were infinity, pi, plus/minus, and theta, and it makes sense that those are not translatable. x and y were left for i18n.

We found that ohms were translatable, I would question why pi or theta would never be translatable and ohms would.

**Comment by pixelzoom** [comment] 2018-12-06 20:02
@zepumph said:
> We found that ohms were translatable, I would question why pi or theta would never be translatable and ohms would.

This seems like an argument for allowing translatable symbols in MathSymbols, so that we could make a symbol translatable without having to change client code.

**Comment by pixelzoom** [comment] 2018-12-13 20:13
12/13/18 dev meeting:

* Make a pass through MathSymbols.  
* Constants for Greek characters (THETA, ROH,...) should not be translatable.  
* Constants for "logical" things (OHMS, RESISTANCE,...) can be translatable. 
* ROH and THETA should probably be change to RESISTIVITY and ANGLE respectively.

**Comment by pixelzoom** [comment] 2018-12-13 20:17
I'll handle fixing up MathSymbols.js. Then assign to @jbphet to work into 1.6 release of RIAW. 

High priority.

**Comment by pixelzoom** [comment] 2018-12-13 21:03
MathSymbols.js has been "fixed up" in the above commit.  

I added `MathSymbols .RESISTIVITY`, for use in RIAW.   The convention I choose for string keys is (e.g.) `"symbol.resistivity`.  @jbphet feel free to change this convention if you prefer something else.  

One note: Things like resistivity and ohms are not technically math symbols, so there's a little dissonance with them being in MathSymbols.js.  But it doesn't bother me enough to want to address it.  @jbphet if you feel otherwise, let me know.

**Comment by KatieWoe** [comment] 2018-12-15 00:06
Confirmed fixed for 1.6.0-rc.2.  It looks like discussion is still going, so I'll let you close if ready @jbphet

**Comment by jbphet** [comment] 2018-12-27 22:01
Some work has been done on this to incorporate the new, translatable, common code symbols.  As a result, this should be re-verified on the next RC.

Also, **do not close this issue** until it has been verified that the translations are correct after publication.  It will likely fall to me to do this.

**Comment by jbphet** [comment] 2019-01-22 19:51
I've just verified the translations on the newly published 1.6.0 version, and they look good.  Closing.

**Closed by jbphet** 2019-01-22 19:51 UTC
Labels: status:fixed-awaiting-deploy, type:bug, type:i18n
