### ISSUE TITLE
NVDA stutters on equation when rho is small and A is stuttered when being controlled

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#175] opened 2018-09-07 15:52 UTC
**Device**
Dell Laptop
**OS**
Win 10
**Browser**
Firefox
**Problem Description**
For phetsims/QA/issues/183
There are some stutters when using the NVDA screen reader.  The first occurs when R and rho are small and the screen reader is describing the equation.  Other states of the equation do not seem to create this stutter so far as I have discovered.  In addition, when manipulating A the screen reader stutters over A itself.
**Steps to reproduce**
1. Turn on NVDA with Firefox
2. Adjust rho so that it is much smaller than L and A.  Some small adjustments can be made to the other values, as can be seen with L in the video.
3. Set the screen reader to describe the equation and listen to the size comparisons
4. Use keyboard nav to adjust the A slider to hear that particular stutter.

**Screen capture**
https://drive.google.com/file/d/1AkQyl84E28N_h4AhZcr_D47iu6R3zQSb/view?usp=sharing
https://drive.google.com/file/d/1aG7S2R7YdAw8yYn1IxdFfALouNgsHovq/view?usp=sharing

**Comment by zepumph** [comment] 2018-09-07 17:52
I'm terribly sorry. I can't hear the stutter. Honestly it sounded normal to me. @jessegreenberg can you hear it?

**Comment by KatieWoe** [comment] 2018-09-07 17:58
The primarily described is in the second video I believe.  The word the is repeated before L.

**Comment by jessegreenberg** [comment] 2018-09-08 16:32
Good ear @KatieWoe! To me it sounds like repetition of the word "than".

**Comment by jessegreenberg** [comment] 2018-09-08 16:33
Here it is in the PDOM: 
![image](https://user-images.githubusercontent.com/6396244/45256360-5c82a480-b363-11e8-8249-9d21ca4a63bd.png)

**Comment by jessegreenberg** [comment] 2018-09-08 16:36
I think the problem is the "than" in `lAndAComparablePatternString`:
'Size of letter R is {{rToRho}} the size of letter rho, and {{rToLAndA}} than letter L and letter A.'

because the size comparison strings all have "than" already.

**Comment by jessegreenberg** [comment] 2018-09-08 16:41
This was my fault @zepumph, so sorry :(

I went ahead and removed it and played with the sim, I think this is safe. Can you please review? I don't think there was a combination that was using that extra "than" but can you please verify before we merge with master?

**Comment by zepumph** [comment] 2018-10-24 23:01
We will not be pulling this into the 1.5 rc. If this has been confirmed fixed in master it can be closed.

**Closed by zepumph** 2018-10-24 23:01 UTC
Labels: dev:a11y, status:fixed-pending-testing
