### ISSUE TITLE
[mirror inputs] Drawing phenomenon when area is minimum

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#112] opened 2017-10-13 21:57 UTC
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.6 (16G29)

**Browser:**

Safari Version 11.0 (12604.1.38.1.7)

**Problem description:**

There is a "drawing" phenomenon when area is minimum. This was discovered testing mirror inputs wrapper. This is for phetsims/QA/issues/53. This is similar to phetsims/resistance-in-a-wire/issues/108.

**Steps to reproduce:**

1. Slide the area to it's minimum value.
2. Move cursor around.

**Screenshots:**

![oct-13-2017 15-50-25](https://user-images.githubusercontent.com/31285590/31567886-dfe1644e-b02e-11e7-9646-3a401a231abd.gif)

**Comment by phet-steele** [comment] 2017-10-14 00:16
@jessegreenberg...I'm going to jump the gun on assuming we will need help from @jonathanolson. Co-assigning to him.

**Comment by jessegreenberg** [comment] 2017-10-24 18:07
In phetsims/ohms-law#68, we added preventFit to fix an issue where components were jostling during use. Really just a shot in the dark, but could that be related?

**Comment by jonathanolson** [comment] 2017-10-27 03:44
This looks like the browser is having issues with how large the font ends up being. Maybe the mouse movement triggers the refresh on the top one (no clue).

Does this happen with rootRenderer=canvas?

**Comment by jessegreenberg** [comment] 2017-10-30 22:37
@jonathanolson I cannot reproduce this problem with rootRenderer=canvas.

**Comment by jessegreenberg** [comment] 2017-10-30 22:44
@jonathanolson is ```renderer: canvas``` for the letters in this sim a recommended fix?

**Comment by jonathanolson** [comment] 2017-10-30 22:59
Forcing that may affect performance and/or font/shape antialiasing.

@ariel-phet, should I look into workarounds for the specific case, so that we wouldn't have to force Canvas in this situation?

**Comment by jonathanolson** [comment] 2017-10-30 23:07
See https://github.com/phetsims/resistance-in-a-wire/issues/108#issuecomment-340611488 for potential workarounds.

**Comment by ariel-phet** [comment] 2017-10-31 19:20
@jonathanolson I am fine with forcing canvas unless it is brutal on performance. My quick look at font shape/aliasing seemed acceptable. I would rather not look into work around if not necessary. 

@jessegreenberg perhaps only force canvas on safari? I would be fine with that

**Comment by jessegreenberg** [comment] 2017-11-02 23:40
One recommendation from  #108 was to rasterize text to images and scale that way. I tried that in #108, but I am still seeing this  problem

**Comment by jessegreenberg** [comment] 2017-11-07 20:17
In #108, this was fixed by rendering with canvas when using safari. Marking as fixed, pending testing.

**Comment by phet-steele** [comment] 2017-11-08 17:28
Fixed in macOS 10.13.1, iOS 11.0.3, and iOS 9.3.5.

**Closed by phet-steele** 2017-11-08 17:28 UTC
Labels: dev:phet-io, status:fixed-pending-testing, type:bug
