### ISSUE TITLE
Pitch changes more on last bit of sliders

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/resistance-in-a-wire#188] opened 2018-11-08 19:53 UTC
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/219#event-1953042350
When listening to the sound made by different increments while moving the sliders, the pitch difference drastically changes when at the bottom of the slider.  If moving the rho or L sliders the last ding is much higher than the others.  If moving the A slider the last ding is much lower than the others.
**Steps to reproduce:**
1. Go to the sim and slowly drag each slider, one by one, to the bottom, while listening to the sounds made.
2. Move the sliders back up to make the comparison in the opposite direction.

**Screenshots:**
https://drive.google.com/file/d/1PEniRuDPT-8Ilo-SSdMJFOH79XFfU_R1/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.0-rc.1/phet/resistance-in-a-wire_en_phet.html
Version: 1.6.0-rc.1 2018-11-07 18:26:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"ff00a0bb","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"fa2fbadf","branch":"HEAD"},"dot":{"sha":"bbbd8526","branch":"HEAD"},"joist":{"sha":"82521d0c","branch":"HEAD"},"kite":{"sha":"380cef53","branch":"HEAD"},"phet-core":{"sha":"1b90ac2f","branch":"HEAD"},"phet-io":{"sha":"38d7b161","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"246085c1","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"7479b0ec","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"c46f7839","branch":"HEAD"},"phet-io-wrappers":{"sha":"a6bc62ca","branch":"HEAD"},"phetcommon":{"sha":"cd63d89a","branch":"HEAD"},"query-string-machine":{"sha":"06ed6276","branch":"HEAD"},"resistance-in-a-wire":{"sha":"38ae25d0","branch":"HEAD"},"scenery":{"sha":"51716674","branch":"HEAD"},"scenery-phet":{"sha":"15dec251","branch":"HEAD"},"sherpa":{"sha":"2cd50500","branch":"HEAD"},"sun":{"sha":"5244d45e","branch":"HEAD"},"tambo":{"sha":"ad355580","branch":"HEAD"},"tandem":{"sha":"4f37a910","branch":"HEAD"}}

</details>

**Comment by emily-phet** [comment] 2018-11-09 19:20
Yup - this maps (reasonably) to the resistance values. There can be some extreme resistance value changes at the extremes of the sliders, and this significant pitch change is intended to reflect that. You should be hearing the most drastic pitch changes when the most drastic visual changes to the letter sizes occur.

**Comment by Ashton-Morris** [comment] 2018-11-09 20:14
Yes I agree with @jbphet adn @emily-phet

**Comment by mikewinters10** [comment] 2018-11-09 22:39
Just confirming: the pitch difference @KatieWoe is describing is consistent with our the logarithmic scaling of R, which maps the 9 orders of magnitude of R onto a linear scale (0 to 1).

> _normR_ = log( _curR_  /  _minR_ ) / log( _maxR_  /  _minR_ )
> Where _normR_ is a normalized resistance value between 0 and 1, _curR_ is the current resistance value of the sim, _minR_ is the minimum amount of resistance in the sim, and _maxR_ is the maximum amount of resistance in the sim.

Because of this function, the small changes in rho, L or A at the bottom of the sliders create proportionally large changes in R, which would create large pitch differences as described.

**Comment by jbphet** [comment] 2018-11-12 16:29
Okay, sounds like the sim is behaving as designed.  Closing.

**Closed by jbphet** 2018-11-12 16:29 UTC
Labels: type:bug
