### ISSUE TITLE
Impurity dots outside of wire

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#170] opened 2018-08-24 17:33 UTC
For https://github.com/phetsims/QA/issues/179. On macOS 10.13.6 + Chrome 68.0.3440.106, I'm seeing this:

![dots_pblm](https://user-images.githubusercontent.com/31285590/44598064-fdcc0100-a78e-11e8-95b3-86ebc435fe68.png)

I can't remember if this was an issue in older versions of the sim before @jessegreenberg implemented ffcefb6ad36f94f606c878e51b0f8ff86f10f7f3.

**Comment by KatieWoe** [comment] 2018-08-24 17:38
Close up image
![outofbounds](https://user-images.githubusercontent.com/41024075/44599035-3a4d2c00-a792-11e8-9951-f0d232687a08.PNG)

**Comment by jessegreenberg** [comment] 2018-08-24 22:06
Good eye, this is definitely new because using a clip shape that includes arcs is more performance intensive.

**Comment by jessegreenberg** [comment] 2018-08-24 22:16
@KatieWoe or @lmulhall-phet can you please see if this is fixed in master?

**Comment by lmulhall-phet** [comment] 2018-08-24 22:41
Looks fixed to me.

**Comment by KatieWoe** [comment] 2018-08-24 22:42
Looks good on my end

**Comment by jessegreenberg** [comment] 2018-08-24 22:46
OK thanks @KatieWoe and @lmulhall-phet, leaving open to make sure this gets into the release branch.

**Comment by KatieWoe** [comment] 2018-09-06 20:45
@zepumph 
For phetsims/QA/issues/183.
It seems like this seems to happen to some small extent still.
Win 10 Chrome
![outside](https://user-images.githubusercontent.com/41024075/45184191-74cbb580-b1e3-11e8-8411-e6e954873991.PNG)

**Comment by zepumph** [comment] 2018-09-06 20:48
From https://github.com/phetsims/resistance-in-a-wire/issues/170#issuecomment-415901065 it makes it seem like this issue is completely fixed in master. @KatieWoe can you confirm that you can't find this "small" version of the bug in master too?

**Comment by lmulhall-phet** [comment] 2018-09-06 21:42
I'm seeing some slight clipping in master on Win10 + Chrome:

![dots](https://user-images.githubusercontent.com/31285590/45186563-27534680-b1eb-11e8-97ea-38b44d9e7c22.PNG)

**Comment by lmulhall-phet** [comment] 2018-09-06 21:44
Found this in master on macOS + Chrome:

![screen shot 2018-09-06 at 3 43 38 pm](https://user-images.githubusercontent.com/31285590/45186720-af395080-b1eb-11e8-8b7a-f72ba81da13b.png)

**Comment by zepumph** [comment] 2018-09-06 21:53
I agree, but I think it is mighty close. @jessegreenberg this may just be adjusting the clip area ever so slightly. A few more comments about what I found in master.

Here is a dot a the edge where it is curved more, and it is a bit off.
![image](https://user-images.githubusercontent.com/6856943/45187045-e56ed400-b1db-11e8-9af9-43181a6e2ae2.png)

Where as this dot is pretty much perfect on the end. I'm not sure it needs any tweaking, but it is on the more gentle part of the curve
![image](https://user-images.githubusercontent.com/6856943/45187118-16e79f80-b1dc-11e8-90a5-a58b40db57fd.png)

Here is another where I cannot decide if it is outside the wire or not,
![image](https://user-images.githubusercontent.com/6856943/45187129-223acb00-b1dc-11e8-90b2-3318d9a5d77b.png)

**Comment by jessegreenberg** [comment] 2018-09-07 14:37
> Edit: I notice that it seems to happen most near the corners of the wire.

That seems to be the most important thing. The clip shape is scaled down by the radius of the dot to prevent this, but maybe that isn't enough for the corners.

**Comment by jessegreenberg** [comment] 2018-09-07 14:57
I am able to reproduce this issue around the rounded corners of the wire if I extend the length of the wire just long enough with the keyboard.

**Comment by jessegreenberg** [comment] 2018-09-07 15:07
If the clip shape gets too small the dots start to look like they disappear too early, which IMO is worse than them extending beyond the edge of corners of the wire by a few pixels. I adjusted the scale by a bit to get a happy medium, @KatieWoe and @lmulhall-phet can you play with master and see if this is better?

**Comment by KatieWoe** [comment] 2018-09-07 21:27
I would agree.  Slight clipping is preferable.  The clipping is better since the issue was first raised.

**Comment by jessegreenberg** [comment] 2018-09-08 20:57
Ok, one more thing we can try is to approximate the arc around the ends of the wire. Using `Shape.ellipticalArc` was performance intensive, but maybe an arc shape with fewer segments will work out faster.

**Comment by jessegreenberg** [comment] 2018-09-08 21:36
Using segments to approximate the clip shape seems to be working well. I tested in JAWS 2018 on my slower laptop in FF 62 and it sounds nice, I can't reproduce #165 or #164. The clip shape looks something like this, though we can increase the number of segments to get a cleaner shape.
![capture](https://user-images.githubusercontent.com/6396244/45258839-b1d3ab80-b38d-11e8-8cef-42a7af030e6b.PNG)

**Comment by jessegreenberg** [comment] 2018-09-08 21:37
With 9 segments on each side, it is plenty fast enough and almost a perfect shape
![capture](https://user-images.githubusercontent.com/6396244/45258849-d29c0100-b38d-11e8-83a8-caed1e88a60a.PNG)

**Comment by jessegreenberg** [comment] 2018-09-08 21:46
The "approximation" will be worst around the corners of the wire. So the current result is that dots that are right at the corners may have a sliver chopped off between the dot and edge of the wire that looks something like this:
![capture](https://user-images.githubusercontent.com/6396244/45258894-c2d0ec80-b38e-11e8-9dd4-a86fbf75f70f.PNG)

But I think this is totally reasonable since we have clean clipping for the rest of the wire, better performance, and no dots that are removed too early.

@KatieWoe @lmulhall-phet can you please review master and comment if you agree or disagree?

**Comment by KatieWoe** [comment] 2018-09-10 14:44
@jessegreenberg I agree, it looks much better.  I noticed the same thing you did in the corners, but on a very high resolution screen I had to squint to notice it.

**Comment by jessegreenberg** [comment] 2018-09-13 15:33
OK, great, thanks. In that case this can be merged into the release branch.

**Comment by jessegreenberg** [comment] 2018-09-13 15:36
I believe that these are the commits that need to go into the release branch:
https://github.com/phetsims/resistance-in-a-wire/commit/1889524314f79fec312219217a8cc286171d670a
https://github.com/phetsims/resistance-in-a-wire/commit/c029514323a0bd7730882a4e86e6ad10bd6ea8c8
https://github.com/phetsims/resistance-in-a-wire/commit/a3278ac15a64d84780417bc740d27c57e04cbb3a

**Comment by zepumph** [comment] 2018-10-24 23:01
We will not be pulling this into the 1.5 rc. If this has been confirmed fixed in master it can be closed.

**Closed by zepumph** 2018-10-24 23:01 UTC
