### ISSUE TITLE
[Android] flickering black spot when area is adjusted

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#158] opened 2018-06-19 19:10 UTC
<b>Test Device</b>

Nye

<b>Operating System</b>

Android 7.0

<b>Browser</b>

Chrome

<b>Problem Description</b>

For phetsims/QA/issues/130. Adjusting area results in black flickering spot in wire. See the video.

<b>Visuals</b>

https://drive.google.com/open?id=1BMRqm18IVXWyJlvCYJSzJQ9RTncFS7HD

**Comment by lmulhall-phet** [comment] 2018-06-19 19:32
Also happens with length. Doesn't seem to matter what the rho value is.

**Comment by zepumph** [comment] 2018-06-19 21:50
Very interesting! @lmulhall-phet does this happen from the published one http://phet.colorado.edu/sims/html/resistance-in-a-wire/latest/resistance-in-a-wire_en.html?@jonathanolson have you seen this before? Does it have something to do with rendering artifacts?

**Comment by lmulhall-phet** [comment] 2018-06-19 21:53
@zepumph, it does occur in production.

**Comment by zepumph** [comment] 2018-06-19 22:10
Repeatable easily in the phet app on my android phone.

**Comment by zepumph** [comment] 2018-06-19 23:31
`rootRenderer=canvas` does indeed "fix" the issue for my android device. I can't make it stay broken, but I'm not the QA master.

**Comment by lmulhall-phet** [comment] 2018-06-20 20:40
@jonathanolson, I can't get it to stay broken. `rootRenderer=canvas` "fixes" the issue for me.

**Comment by jonathanolson** [comment] 2018-06-20 21:55
@ariel-phet how should we proceed?

Working around it would involve some combination of trying imperceptible changes to the path, trying to come up with an easily reproducible example, etc.

**Comment by lmulhall-phet** [comment] 2018-06-21 01:30
I should note that rootRenderer=canvas drops the performance somewhat.

**Comment by jonathanolson** [comment] 2018-06-21 02:44
Implemented above (just making the needed part Canvas instead of everything). Let me know if performance is not acceptable due to the change.

**Comment by zepumph** [comment] 2018-06-21 17:24
I'll add this to a another RC so that @lmulhall-phet can test performance appropriately.

**Comment by zepumph** [comment] 2018-07-10 21:19
@lmulhall-phet in phetsims/QA#137 (comment) you said that QA is done, so I assume that I'm good to close this issue, and that it was successfully checked.

**Closed by zepumph** 2018-07-10 21:19 UTC
Labels: status:ready-for-review, type:bug

**Comment by lmulhall-phet** [comment] 2018-07-10 21:22
@zepumph, sorry, yes it seems to be fixed.
