### ISSUE TITLE
Issues with String Tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/resistance-in-a-wire#63] opened 2016-01-15 20:23 UTC
Related to https://github.com/phetsims/tasks/issues/479

Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Chrome 47.0.2526.106

Problem description: Issues with Long strings. Minor detail in rtl test, don't know if it is significant.

Steps to reproduce: Perform string tests

Severity:

Screenshots:
Long:
![screen shot 2016-01-15 at 1 20 00 pm](https://cloud.githubusercontent.com/assets/12610678/12364328/28d4f822-bb8b-11e5-9ecb-b909371b7abc.jpg)

rtl:
![screen shot 2016-01-15 at 1 21 05 pm](https://cloud.githubusercontent.com/assets/12610678/12364331/2f67cce6-bb8b-11e5-8c90-ed695d0c517c.jpg)

Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: http://phettest.colorado.edu/resistance-in-a-wire/resistance-in-a-wire_en.html?ea&brand=phet&showPointerAreas
Version: 1.2.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1268x653
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by elisemorgan** [comment] 2016-03-02 18:20
@jbphet  double string test related to https://github.com/phetsims/tasks/issues/531 
![screen shot 2016-03-02 at 11 17 36 am](https://cloud.githubusercontent.com/assets/12610678/13470283/b22787d2-e068-11e5-8e56-ceeb4830bf9d.jpg)

**Comment by elisemorgan** [comment] 2016-03-02 18:23
Related to https://github.com/phetsims/tasks/issues/531
@jbphet Is it intentional that the symbols turn into 1's on the long string test? I don't think I've seen this happen before 
![screen shot 2016-03-02 at 11 22 41 am](https://cloud.githubusercontent.com/assets/12610678/13470370/1a1ec4a4-e069-11e5-9193-9232fecf817e.jpg)

**Comment by jbphet** [comment] 2016-03-03 23:40
I did some investigation on this and the problem is unique to pattern strings.  It can be eliminated by turning on the call to ```simplifyEmbeddingMarks``` in StringUtils.format (currently only called when running on the Edge browser).  However, this would have some effect on performance, and since doubling of strings in patterns is not something that real world users - including translators - are ever going to do, we should just see this as a non-issue.  I'm going to label this as "won't fix" and close.

**Closed** 2016-03-03 23:41 UTC
Labels: task:S2015R, type:i18n, type:wontfix

**Comment by jbphet** [comment] 2016-03-04 17:05
By the way, I tested this on Win10 + Chrome, Firefox, and Edge and the problem did not occur there.  I was only able to reproduce on iOS 9.2.1.  I didn't try it on OSX.
