### ISSUE TITLE
Links break if cursor sticks to slider and links are clicked

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#148] opened 2018-05-24 20:38 UTC
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.13.4

<b>Browser</b>

Firefox 60.0.1

<b>Problem Description</b>

For phetsims/QA/issues/118. If you follow the steps for #147, click the "PhET Website" link or the "Report a Problem" link, and return to the simulation, then the link you clicked won't work anymore.

<b>Steps to Reproduce</b>

1. Make sure your cursor is stuck to the thumb of the slider. See #147.
2. Click the PhET Menu button.
3. Click the "PhET Website" link or the "Report a Problem" link.
4. Return to the simulation.

<b>Visuals</b>

![riawpw](https://user-images.githubusercontent.com/31285590/40512070-eb4bec52-5f5e-11e8-8542-2a8b6b0ad722.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.3/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.3 2018-04-26 19:12:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1440x723
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"54f17be2","branch":"HEAD"},"dot":{"sha":"0dd6ee8e","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"6b2924cf","branch":"HEAD"},"scenery":{"sha":"64f0c409","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"6a7c923a","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

</details>

**Comment by phet-steele** [comment] 2018-05-24 20:57
@lmulhall-phet you are very likely just experiencing phetsims/balloons-and-static-electricity/issues/406, and it would have nothing to do with #147.

**Comment by lmulhall-phet** [comment] 2018-05-24 21:03
@phet-steele, I think you're right. I looked at the console and didn't see an error, which is probably what lead me to think that it wasn't phetsims/balloons-and-static-electricity/issues/406.

**Comment by lmulhall-phet** [comment] 2018-05-24 21:07
@jonathanolson and @zepumph I suppose we can close this issue if no one objects.

**Comment by phet-steele** [comment] 2018-05-24 21:11
> @phet-steele, I think you're right. I looked at the console and didn't see an error, which is probably what led me to think that it wasn't phetsims/balloons-and-static-electricity#406.

Remember, you will not see errors in non-debug, built sims (rc, dev, etc...). You will only see errors in non-built or debug sims (...phet_debug.html [the BASE issue], phettest, etc)

**Comment by zepumph** [comment] 2018-05-24 23:07
>Remember, you will not see errors in non-debug, built sims (rc, dev, etc...). You will only see errors in non-built or debug sims (...phet_debug.html [the BASE issue], phettest, etc)

This makes me think that we don't need to cherry pick any changes into this RIAW branch for production deploy, is that right?

**Comment by lmulhall-phet** [comment] 2018-05-25 15:08
> This makes me think that we don't need to cherry pick any changes into this RIAW branch for production deploy, is that right?

@zepumph, That sounds right to me, but I would defer to @phet-steele's wisdom on this one.

**Comment by phet-steele** [comment] 2018-05-25 16:05
> This makes me think that we don't need to cherry pick any changes into this RIAW branch for production deploy, is that right?

The sim still breaks when clicking those external links à la phetsims/balloons-and-static-electricity/issues/406 and I do see errors in the phet_debug.html. If RIAW doesn't have the fix from there yet, it would be useful to cherry-pick that.

Just because an error is not reported in the console doesn't mean the sim is immune to breaking. Besides, this issue was logged explicitly due to breaking from phetsims/balloons-and-static-electricity/issues/406, so why would we choose to not cherry-pick the fix for that, ever?

**Comment by zepumph** [comment] 2018-05-25 18:08
After talking with @jonathanolson, it looks like the following shas need to be cherry-picked into the branch:
```
5f9de2fc392e650760b9b5dadbdcb31a389f5f9c
339eb5a43283e002fa1491608cc482414a4f430b
76a0f84bfde0d2258d45d36c11f0289d877e8144
8497d456d2960e04bea81bdf5db9c84bca67e6ce
993223363d5eb8c0f7ef297617fe0d093e39b3c2
588f22fbe57a638954e2ab54b623906e92bdc1ea
61536f61617372100ac2bfc71509a45b7f5e1dfe
fd5152a2120d469fa161582f56f2c360f5121fde
b5240b0139a52df0e764d809f07b21b3d9461423
ebc23be5a2e45e02aaa1e94c7e64c95aa176e292
```
@jonathanolson was wondering (a) if it wasn't work just doing a new rc from master or (b) if this needs to be added to this branch.

Without full knowledge of the issue, I would recommend that if these commits successfully cherry pick into our scenery branch for RIAW, then I do so and we carry on happily. Otherwise and tentatively, I think that we should proceed with this RC over creating a new RC from master, because that would involve much more QA time. 

NOTE: much will depend on how https://github.com/phetsims/scenery/issues/803 goes, because that will need to be added to this RC branch too.

**Comment by ariel-phet** [comment] 2018-05-31 18:17
Changing label to `status:ready-for-review`

**Comment by lmulhall-phet** [comment] 2018-06-04 19:17
For future reference, I would like to make it clear that this issue contains **_TWO SEPARATE ISSUES_**:
1. Cursor Sticking Issue (documented here https://github.com/phetsims/resistance-in-a-wire/issues/147)
2. Links Breaking Simulation Issue (documented here https://github.com/phetsims/balloons-and-static-electricity/issues/406)

(Sorry about that.)

**Comment by zepumph** [comment] 2018-06-22 18:47
@lmulhall-phet I'm seeing that this issue was never specifically mentioned as fixed as part of rc.5, but I assume that by the checkmark in https://github.com/phetsims/QA/issues/125 that this was confirmed fixed for both of the above issues. Closing.

**Closed by zepumph** 2018-06-22 18:48 UTC
Labels: status:ready-for-review, type:bug, type:duplicate

**Comment by lmulhall-phet** [comment] 2018-06-22 18:50
@zepumph, sorry! Yes, this was fixed.
