### ISSUE TITLE
Esc Does Not Exit Key Nav Shortcuts Menu

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/resistance-in-a-wire#206] opened 2019-01-17 17:31 UTC
For https://github.com/phetsims/QA/issues/257 when testing the sim on Windows 10 using the "esc" button to close the keyboard shortcuts menu does not work unless the "x" button in the top right is highlighted via tab navigation. The same issue occurs when viewing the about menu in the PhET menu. This is quite a small issue as the menu can be closed by simply clicking the "x" or clicking outside of the menu area, but could cause confusion for users using a screen reader expecting the menu to close by using the "esc" key. In addition if the sim is in full screen mode and the keyboard shortcuts menu is opened, even if the "x" is highlighted hitting "esc" will exit full screen mode, then another "esc" will exit the menu. I'm not sure if this is the intended behavior but something I noticed while testing this bug.

**Comment by arouinfar** [comment] 2019-01-17 17:52
> the "esc" button to close the keyboard shortcuts menu does not work unless the "x" button in the top right is highlighted via tab navigation

I believe this what @JRomero0613 reported in https://github.com/phetsims/coulombs-law/issues/94, which is actually the intended behavior for keyboard navigation. Escape exits a dialog only when its close button has keyboard focus.

> if the sim is in full screen mode and the keyboard shortcuts menu is opened, even if the "x" is highlighted hitting "esc" will exit full screen mode, then another "esc" will exit the menu.

Interesting find @JRomero0613. This does sound a bit odd to me. I was able to reproduce when the sim was in full screen mode (PhET menu > Full Screen) on macOS 10.13.6/latest Chrome. It would seem more natural if the first esc press exited the dialog, rather than exiting full screen mode. I'm not sure if that's possible @jbphet.

**Comment by jbphet** [comment] 2019-01-22 16:41
Thanks for the updates everyone, closing.

**Closed by jbphet** 2019-01-22 16:41 UTC
Labels: type:bug
