### ISSUE TITLE
Slider is sticking

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/resistance-in-a-wire#147] opened 2018-05-23 22:27 UTC
<b>Test Device</b>

Hanson, MacBook Air

<b>Operating System</b>

Windows 10, macOS

<b>Browser</b>

Windows 10:
- Firefox 60.0.1
- Microsoft Edge 42.17134.1.0

macOS:
- Firefox 60.0.1
- Google Chrome 66.0.3359.181
- Safari 11.1

<b>Problem Description</b>

For phetsims/QA/issues/118. Minor issue. I can get the slider to stick to the cursor.

<b>Steps to Reproduce</b>

1. Left click on a slider thumb and then very quickly right click on the slider.
2. Click outside of the simulation.

EDIT: Should have mentioned that I did this with a mouse.

<b>Visuals</b>

![riaw](https://user-images.githubusercontent.com/31285590/40453943-276c3eaa-5ea4-11e8-9718-383c1303638f.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.3/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.3 2018-04-26 19:12:59 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1280x606
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"54f17be2","branch":"HEAD"},"dot":{"sha":"0dd6ee8e","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"6b2924cf","branch":"HEAD"},"scenery":{"sha":"64f0c409","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"6a7c923a","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

</details>

**Comment by zepumph** [comment] 2018-05-24 16:49
I was able to reproduce this on Chrome Version 66.0.3359.181 (Official Build) (64-bit) too.

1. left click then right click quickly on the slider
2. left click outside the sim, like on the chrome top bar.
3. slider will now be stuck, and the right click menu is not there.

@jonathanolson do you have any insight on this?

**Comment by jonathanolson** [comment] 2018-05-24 16:57
I'll definitely investigate. Two questions first:

1. Can I reproduce this with a touchpad (macOS)? Don't know if the quick-right-click is fast enough, or if it needs to start before the left click ends.
2. Is this broken in master? Recent input work may have fixed this, since it seems related to my recent fixes.

**Comment by lmulhall-phet** [comment] 2018-05-24 18:55
1. I'll be impressed if anyone _\*cough\*_ @phet-steele _\*cough\*_ can reproduce this issue with a trackpad.
2. It seems to be broken in master.

**Comment by zepumph** [comment] 2018-05-24 19:53
Let me know if there is anything else I can do to support or implement.

**Comment by phet-steele** [comment] 2018-05-24 21:04
@lmulhall-phet this has been a general problem in all sims, thanks for being less lazy than me and logging it (@jonathanolson this is essentialy https://github.com/phetsims/molecule-shapes/issues/127 and the related issues).

> Can I reproduce this with a touchpad (macOS)? Don't know if the quick-right-click is fast enough, or if it needs to start before the left click ends.

Two things:

- Yes you can use a touchpad. Use one finger to drag, then two other fingers to right click.
- Speed is not a factor in this issue at all.

**Comment by lmulhall-phet** [comment] 2018-05-24 21:14
Thanks, @phet-steele. I haven't been able to reproduce with a trackpad, but I would imagine doing so would require the `System Preferences > Trackpad > Tap to click` setting. Also haven't been able to reproduce without speed being a factor.

**Comment by lmulhall-phet** [comment] 2018-05-24 21:39
Not sure how useful this is, but I encountered some bizarre behavior with the Reset All button:
![riawrb](https://user-images.githubusercontent.com/31285590/40515051-8d38a6e6-5f68-11e8-8c13-69258032969d.gif)

**Comment by jonathanolson** [comment] 2018-05-25 00:50
Hmm, the Chrome bug likely to have caused the molecules-and-shapes issue presumably would only happen in an iframe (https://bugs.chromium.org/p/chromium/issues/detail?id=269917).

**Comment by jonathanolson** [comment] 2018-05-25 02:33
Hmm, we're not getting the pointerup/pointercancel events (bleh), but since we're setting pointer capture, we seem to be getting a lostpointercapture event. I'll need to look into whether this can reliably be used to fire a scenery-side cancel (and then we could potentially just flat-out ignore an "up" before a down).

**Comment by ariel-phet** [comment] 2018-05-30 17:18
Sure...this is a bit odd. 

And...it is completely curable with a single click. I was able to reproduce the issue and get the cursor stuck, but a single click "unsticks" it. 

This should not be a blocking issue for this release (this issue exists in the published version, and probably occurs in all sims as it is a scenery issue). I will discuss the scenery issue with @jonathanolson but marking this as "won't fix" and closing.

**Closed by ariel-phet** 2018-05-30 17:18 UTC
Labels: type:bug
