### ISSUE TITLE
adjusting sliders leaves trail of letter behind

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/resistance-in-a-wire#150] opened 2018-05-31 20:22 UTC
Test device: PC Laptop

Operating System: Windows 10 OS 17134.48

Browser: Chrome V. 67.0.3396.62

Problem description: For phetsims/QA#125 When using the sliders to adjust the values of resistivity and length sometimes the letters leave behind a small trace that persists until another slider is moved. This is particularly noticeable when performing the right to left query parameter test. 

Steps to reproduce: 
1. Start the simulation in either a full size window or full screen (it might work in a smaller window but the trace is too small and light to see when not in full screen)
2. Adjust either the resistivity or length sliders from a larger value to a smaller value. (the length slider left behind a trace a couple of times, but it is much harder to reproduce than the resistivity slider)
3. There should be a trace left behind by the string (note that the trace varies in length, darkness, and sometimes doesn't appear at all)

Screenshots: As you can see in the GIF below the bug does not occur every time and is random in the length and darkness of the trace. The screenshot shows a different trace that is easier to see than the video. 

![riaw_trace](https://user-images.githubusercontent.com/30352536/40805232-d6e9d536-64da-11e8-80c6-c13986a2b725.gif)

![riaw_trace](https://user-images.githubusercontent.com/30352536/40805999-5775a192-64dd-11e8-9cc2-c9aafb5c9f24.JPG)

Troubleshooting information (do not edit):
Name: ‪Resistance in a Wire‬
URL: https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.5.0-rc.5/phet/resistance-in-a-wire_all_phet.html
Version: 1.5.0-rc.5 2018-05-31 01:31:21 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"cc053b4d","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"54f17be2","branch":"HEAD"},"dot":{"sha":"0dd6ee8e","branch":"HEAD"},"joist":{"sha":"f047fb1b","branch":"HEAD"},"kite":{"sha":"b6071478","branch":"HEAD"},"phet-core":{"sha":"f35ff65e","branch":"HEAD"},"phet-io":{"sha":"d54be499","branch":"HEAD"},"phet-io-website":{"sha":"28284828","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"HEAD"},"phet-io-wrappers":{"sha":"ce57c3e2","branch":"HEAD"},"phetcommon":{"sha":"a5a7478c","branch":"HEAD"},"query-string-machine":{"sha":"485e174e","branch":"HEAD"},"resistance-in-a-wire":{"sha":"f80c6036","branch":"HEAD"},"scenery":{"sha":"33290b5e","branch":"HEAD"},"scenery-phet":{"sha":"42b0cff2","branch":"HEAD"},"sherpa":{"sha":"9c6ec322","branch":"HEAD"},"sun":{"sha":"6a7c923a","branch":"HEAD"},"tandem":{"sha":"7f499d9e","branch":"HEAD"}}

**Comment by zepumph** [comment] 2018-05-31 20:45
I was not able to reproduce this until I made `R` and `L` tiny, and `A` huge, then moving rho consistently made a large trail, @jonathanolson do you have any ideas on this? Reproducible in master for me as well.

Chrome Version 67.0.3396.62 (Official Build) (64-bit), OS WIndows 10

**Comment by jonathanolson** [comment] 2018-05-31 23:39
Looks like a standard SVG "dirty region" bug. Probably can be worked around by adding a transparent rectangle around the letter (so that it repaints more). Presumably `?rootRenderer=canvas` will prevent this also.

**Comment by zepumph** [comment] 2018-06-01 00:16
Confirmed that `rootRenderer=canvas` fixes the problem. This has happened before, and was addressed in https://github.com/phetsims/ohms-law/issues/26, but only for the X axis, so I adjusted the fix to work here as well (`dilatedX` --> `dilated` ). I also fixed ohms law.

@JRomero0613 can you confirm the fix has worked in master here: http://phettest.colorado.edu/resistance-in-a-wire/resistance-in-a-wire_en.html?ea&brand=phet?

**Comment by JRomero0613** [comment] 2018-06-01 15:33
@zepumph This new version in master has fixed the issue, I'm not seeing any traces left behind by any letters

**Comment by zepumph** [comment] 2018-06-01 16:36
Leaving open to confirm that the fix is properly cherry picked into the next RC version.

**Comment by zepumph** [comment] 2018-06-19 20:50
@lmulhall-phet I did not receive confirmation that this was confirmed fixed (at least here), but you passed the qa issue (phetsims/qa#130) to me, so I am going to close this issue. Please reopen if you need to.

**Closed by zepumph** 2018-06-19 20:50 UTC
Labels: status:fixed-pending-testing, type:bug

**Comment by lmulhall-phet** [comment] 2018-06-22 19:05
@zepumph, again sorry. According to @JRomero0613, this is fixed. I will double check.

**Comment by zepumph** [comment] 2018-06-22 19:12
No need for apologies! All is good.

**Comment by JRomero0613** [comment] 2018-06-22 19:19
Yes, this issue has not been seen in the latest RC version

**Comment by lmulhall-phet** [comment] 2018-06-22 20:46
> this issue has not been seen in the latest RC version

Confirmed.
